services:
  web:
    image: ghcr.io/bindzo8in/:latest
    container_name: bindzo8-web
    restart: unless-stopped

    init: true

    env_file:
      - .env

    networks:
      - web_network

networks:
  web_network:
    external: true