allowBuilds:
  '@parcel/watcher': true
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
overrides:
  "@types/react": "19.2.17"
  "@types/react-dom": "19.2.3"
