import type { Metadata } from "next";
import { Geist, Geist_Mono, Kumbh_Sans, Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/components/session-provider";
import FixedQuoteButton from "@/components/contact-button";
import FloatingWhatsApp from "@/components/floating-whatsapp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kumbhSans = Kumbh_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-kumbh',
});

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-raleway',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${kumbhSans.variable} ${raleway.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col pt-[75px] sm:pt-[96]">
        <AuthProvider>
          <Navbar />
          {children}
          <Footer />
          <FixedQuoteButton />
          <FloatingWhatsApp
            phoneNumber="919884344503"
          />
        </AuthProvider>
      </body>
    </html>
  );
}
